version: '3'

services:


  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080