FROM ubuntu:16.04
LABEL maintener="kropaczmarcin@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    python3 \
    python3-pip \
    python3-tk \
    vim \
    mc \
    libmysqlclient-dev
    && apt-get clean

RUN pip3 install --upgrade pip 
RUN pip3 install \
    sqlalchemy \
    mysqlclient