package pbd.entity;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.PrimaryKey;

@PersistenceCapable
public class Quest {
    @PrimaryKey
    private String title;

    @Column(allowsNull = "false")
    private String description;

    @Column(allowsNull = "false")
    private Action requiredAction;


//    @Column(allowsNull = "false")
//    private Player performer;
//
//    @Column(allowsNull = "false")
//    private NPC principal;


    public Quest(String title, String description, Action requiredAction) {
        this.title = title;
        this.description = description;
        this.requiredAction = requiredAction;
    }

    public static String[] questDescritpion =
            {"Please excuse me, champion. I need a favor of you. Fighting those filthy vermin who dare challenge our empire is both a great honor and a pleasure. However, it seems they have grown in strength lately thanks to some new siege weapon. Hero, seek out that weapon and destroy it. Kill any who stand in your way, we'll teach a lesson or two to those vicious brutes. I offer you my assistance, but it's up to you if you want me to join you or not. I don't think you'll have much troubles dealing with those brutes. Kill as many of them as you'd like, just make sure you don't forget your main goal. I had hoped I'd be able to reward you handsomely, but unfortunately I don't have a lot left. Be swift and strike true hero, we're counting on you.",
                    "Please, hero. I'm in need of your assistance.  I've been betrayed, betrayed by my own foolishness. I knew I shouldn't have hired mercenaries, instead of fighting the enemy they joined them. Hero, teach them a lesson in honor and make sure they remember it. Curse those nasty creatures. If you think you'll need any help, I'm willing to come along. Hero, act swiftly when dealing with the creatures. I'm not asking you to kill all of them, just make sure you do what I ask of you. Should you succeed I will be able to repay you handsomely, it'll be worth your troubles. You best get going, there's no time to waste. We're counting on you.",
                    "Pardon me, champion. Would you lend me your aid.  The other day I caught a huge fish. It was enormous! And by enormous I mean it was the biggest fish I've ever seen, it was probably the biggest fish anybody has ever and will ever see. Unfortunately, after I managed to catch it, the fish got away. It took my fishing rod with it and I really need it back. I'd go and get it myself, but it's underwater and I'm pretty sure that fish has a vendetta against me now. Would you mind getting it for me? Unfortunately there's not much I have to reward you with, but I think there's a few bits and pieces laying around.",
                    "Forgive me, traveler. I could really use a helping hand.  I need to do more research, a lot more research and for that I need my books. All of my books are neatly organized in my library, but my legs aren't what they used to be, I can no longer climb the ladders to reach the upper shelves. Please, would you be so kind and fetch me the books I need. My research is very important after all. I'll be able to reward you decently, it's nothing fancy, but it'll be worth your while.",
                    "Scuse me, hero. Please, lend me your hand. A recent outbreak of some weird disease has caused the townsfolk to go insane. Unfortunately we have no cure and their disease will lead to a painful death. Hero, I know this is a terrible task to ask of you, but we need you to end their suffering. Know that we found who's responsible, we'll get those abominable barbarians. If you think you'll need any help, I'm willing to come along. Be strong and swift when fighting the barbarians. Try to take down as many of them as possible, the less of a threat they pose the better. I wish I had something better to reward you with, but what I have ain't too bad either. For justice and honor!",
                    "Forgive me, champion. I need you to intervene. Seven years it has been, seven years since we secured our lands and we could live in peace. But now they're back and they're stronger than ever. Hero, we'll need your help to get rid of those vile brutes. It'll be dangerous, but I'm willing to come along if you need me to.I don't think you'll have much troubles dealing with those brutes. Make sure they regret the day they ever set foot in our lives. I had hoped I'd be able to reward you handsomely, but unfortunately I don't have a lot left. Safe journey, hero. We believe in you.",
                    "Excuse me, traveler. Help out a person in need. The time to strike is now, but we're low on manpower, so I need you to join us. If we don't strike now, we'll never get rid of them. Join us and fight those terrible barbarians. I'd love to join you, but it'll be up to you. I don't want to get in the way. Tread carefully hero, only a fool would underestimate the barbarians. Killing them all won't be needed of course, I'm sure your skills will do enough damage to them. I'm afraid there's not much left I can reward you with, but I think I can still make it worth your troubles. Please succeed hero, we believe in you.",
                    "Excuse me, adventurer. Spare me some of your time.We're on the offensive at last, but the battle has not been won just yet. To win we will have to go all out and we can use every fighter we can get. Hero, join us and help us kill those wretched trolls. I won't be able to join you, but I have full confidence in you. I know you'll succeed.We're counting on you to deal with those trolls. You don't have to kill them all, just make sure they'll never return.I hope you're not looking for a big reward, but we'll still be able to reward you with somethind decent. Make haste hero, but tread carefully.",
                    "Please excuse me, champion. Help out a person in need. I love the feeling of moss beneath my feet, it's probably the greatest feeling ever. Now, I've come up with a plan which will cover the floors of my house in moss, so I can always experience the greatest feeling ever. The best moss grows in darkwood forest to the South, but I'm too scared to go in there and get the moss myself. It's so dark and creepy in there. Could you gather the moss for me?I had hoped I'd be able to reward you handsomely, but unfortunately I don't have a lot left.",
                    "You there, adventurer. You're a sight for sore eyes.A storm is coming and it's no ordinary storm. A war is upon is, but we're not ready yet. This is where you come into our plan. We need you to take a small party and sabotage the incoming army, that'll give us enough time to deal with those worthless miscreants. I had hoped I could you join, but unfortunately I cannot. But I doubt you'd need my help anyway.You are fully capable to handle those miscreants. If you can, kill as many of them as possible. We want to live in peace and safety.I have little possessions left, but I'll reward you with what I have. Be swift and strike true hero, we're counting on you.",
                    "Pardon me, champion. Please, lend me your hand. As you can see these lands have been corrupted. For the longest time we didn't know what caused it, but now we do. It's the vile magic used by those wicked beings at the foot of the mountains. Hero, please go there and get rid of them before they taint everything, get rid of those disgusting aliens. I'll join you, if you'll have me. It'll be my pleasure. Hero, act swiftly when dealing with the aliens. Killing them all won't be needed of course, I'm sure your skills will do enough damage to them. Unfortunately there's not much I have to reward you with, but I think there's a few bits and pieces left. Please succeed hero, we believe in you.",
                    "Excuse me, hero. Help out a person in need. My daughter has fallen sick and she has to stay in bed for a few more days, but she really wants to go out and play. So I thought, why not bring the outside to her. Unfortunately I cannot leave her, she needs me to be here. Would you mind collecting some objects from outside? She really looves the beach and the forest, so a great big seashell and some colorful flowers are sure to cheer her up.I will be able to reward you greatly, if you decide to help me of course.",
                    "Please, champion. I need your help.Seven years it has been, seven years since we secured our lands and we could live in peace. But now they're back and they're stronger than ever. Hero, we'll need your help to get rid of those vicious humans. If you think you'll need any help, I'm willing to come along.I don't think you'll have much troubles dealing with those humans. Try to take down as many of them as possible, the less of a threat they pose the better.Fortunately I have enough left to reward you greatly for the efforts you have to go through. Best of luck hero, make sure you return in one piece.",
                    "Pleease excuse me, adventurer. I need you to save us.Eye for an eye! Blood for blood! If they wish to play dirty, so will we. Hero, you've seen what they've done to our lands, it's time to unleash our vengeance upon those horrible lowlives. I wish I could join you, but alas I cannot. Know that I've put all my faith in you, you will succeed. I know it.Be strong and swift when fighting the lowlives. Make sure they regret the day they ever set foot in our lives. Unfortunately there's not much I have to reward you with, but I think there's a few bits and pieces left. For justice and honor!",
                    "Scuse me, champiion. Please, help me out.I craft jewelry for a living, but I'm running out of jewels. My old supplier hasn't returned in months and I have no idea what happened to him, but I really need more gems. I heard there's quite a lot of them in the abandoned mines to the North, but I cannot leave my shop, what if a customer comes along? Would you be so kind and gather me some gems, I doubt that abandoned mine is dangerous, it's just a mine.I'm happy to say I'll be able to reward you handsomely for your troubles.",
                    "Please excuse me, hero. Please, lend me your hand.They've burned down half our village with wicked sorcery. Hero, I don't know what foul magic they wield, but we cannot let them go unpunished. Please unleash justice upon those cruel orcs. I'll be coming along with you, at least, as long as you don't mind.You are fully capable to handle those orcs. Kill as many of them as you'd like, just make sure you don't forget your main goal.I will be able to reward you greatly, should you return successfully. You best get going, there's no time to waste. We're counting on you.",
                    "Please, adventurer. I need a favor of you.A storm has destroyed part of our museum, a terrible tragedy. All of those relics, covered in rubble once again or worse, they might be destroyed. We're still working on clearing the rubble, but it's taking too long, those relics have to be recovered before they destroyed forever. Please, hero, find as many relics as you can, but be careful! There's a lot of loose rubble, don't get caught by surprise.I had hoped I'd be able to reward you handsomely, but unfortunately I don't have a lot left.",
                    "You there, traveler. I need a favor of you.I know your efforts were a big driving force in pushing back the enemy, but I'm afraid I must ask even more of you now. It's true, the enemy is on the run, but we'd be fools to let them run and regroup. Hero, I need you to do the dirty work. Seek them out and get rid of those nasty trolls. I'd love to join you, but it'll be up to you. I don't want to get in the way.They'll be no match for you, those trolls. Kill as many of them as you'd like, just make sure you don't forget your main goal.I hope you're not looking for a big reward, but we'll still be able to reward you with somethind decent. Make haste hero, but tread carefully.",
                    "You there, champion. You're a sight for sore eyes.I'm afraid some of our scouts have been captured. We never leave one of our own behind, so we must free them, but sending in a small army will be the death of them for sure. Those monsters will kill our scouts once they see us, they take no risks. So we need you to go on your own, infiltrate their camp and save our troops. Curse those ugly aliens. I wish I could join you, but alas I cannot. Know that I've put all my faith in you, you will succeed. I know it.Please, take care of those aliens. Killing them all won't be needed of course, I'm sure your skills will do enough damage to them.It pains me to say I won't be able to reward you with a lot, but I'll do my best to make it worth your while. I'm looking forward to your return, hero. Good luck.",
                    "Excuse me, champion. Hear me out for a minute.There was once a noble order of druids who lived in the nearby forest. They still live there, but they are no longer noble, far from it. Their rituals seem more demonic than anything else and we cannot let them go on. Hero, please get rid of those disgusting lowlives. I won't be able to join you, but I have full confidence in you. I know you'll succeed.Be strong and swift when fighting the lowlives. There's no need to kill all of them, just put the fear in them.Unfortunately there's not much I have to reward you with, but I think there's a few bits and pieces left. Make haste hero, but tread carefully.",
                    "Pardon me, hero. Would you lend me your aid.We're completely overwhelmed. The war is at its peak and more and more injured come into our hospital in search of aid, but we're running low in supplies. None ofus can afford to leave the injured to seek out more supplies, so we need you to do so. Please gather Peaceblossom, sea urchin needles, silkweb and honey.I will be able to reward you greatly, if you decide to help me of course.",
                    "Please, hero. Spare me some of your time.I'm surrounded by cowards. We were robbed by a group of vermin, they took all they could and killed most of those who tried to stop them. I did what I could, but if everybody helped we would've overpowered them easily. Hero, please retrieve our goods and get rid of those treacherous miscreants. My duties prevent me from going with you, but I doubt I'd be needed anyway.I'm sure you're capable to deal with those miscreants. Make sure they regret the day they ever set foot in our lives. I have little possessions left, but I'll reward you with what I have. Blessed journey champion, may you return swiftly and in one piece."};


}
